/**
 * Generated by Agitar build: Agitator Version 1.0.4.000276 (Build date: Mar 27, 2007) [1.0.4.000276]
 * JDK Version: 1.5.0_09
 *
 * Generated on 04-Apr-2007 08:23:24
 * Time to generate: 00:07.639 seconds
 *
 */

package agitar.uk.ac.ebi.intact.modelt;

import uk.ac.ebi.intact.model.*;

import com.agitar.lib.junit.AgitarTestCase;
import uk.ac.ebi.intact.model.util.AnnotatedObjectUtils;

public class CvExperimentalRoleAgitarTest extends AgitarTestCase {

    static Class TARGET_CLASS = CvExperimentalRole.class;

//    public void testConstructor() throws Throwable {
//        Institution owner = new Institution( "testcvExperimLabel" );
//        CvExperimentalRole cvExperimentalRole = new CvExperimentalRole( owner, "testcvExperimLabel" );
//        assertEquals( "cvExperimentalRole.xrefs.size()", 0, cvExperimentalRole.xrefs.size() );
//        assertEquals( "cvExperimentalRole.getAliases().size()", 0, cvExperimentalRole.getAliases().size() );
//        assertEquals( "cvExperimentalRole.getEvidences().size()", 0, cvExperimentalRole.getEvidences().size() );
//        assertEquals( "cvExperimentalRole.shortLabel", "testcvExperimentalRoleS", cvExperimentalRole.getShortLabel() );
//        assertEquals( "cvExperimentalRole.annotations.size()", 0, cvExperimentalRole.annotations.size() );
//        assertSame( "cvExperimentalRole.getOwner()", owner, cvExperimentalRole.getOwner() );
//        assertEquals( "cvExperimentalRole.references.size()", 0, cvExperimentalRole.references.size() );
//    }

    public void testConstructorThrowsIllegalArgumentException() throws Throwable {
        try {
            new CvExperimentalRole( new Institution( "testcvExperimLabel" ), "" );
            fail( "Expected IllegalArgumentException to be thrown" );
        } catch ( IllegalArgumentException ex ) {
            assertEquals( "ex.getMessage()", "Must define a non empty short label", ex.getMessage() );
            assertThrownBy( AnnotatedObjectUtils.class, ex );
        }
    }

    public void testConstructorThrowsNullPointerException() throws Throwable {
        try {
            new CvExperimentalRole( new Institution( "testcvExperimLabel" ), null );
            fail( "Expected NullPointerException to be thrown" );
        } catch ( NullPointerException ex ) {
            assertEquals( "ex.getMessage()", "Must define a non null short label", ex.getMessage() );
            assertThrownBy( AnnotatedObjectUtils.class, ex );
        }
    }
}