/**
 * Generated by Agitar build: Agitator Version 1.0.4.000276 (Build date: Mar 27, 2007) [1.0.4.000276]
 * JDK Version: 1.5.0_09
 *
 * Generated on 04-Apr-2007 08:28:07
 * Time to generate: 00:07.378 seconds
 *
 */

package agitar.uk.ac.ebi.intact.modelt; import uk.ac.ebi.intact.model.*;

import com.agitar.lib.junit.AgitarTestCase;
import uk.ac.ebi.intact.model.util.AnnotatedObjectUtils;

public class CvTissueAgitarTest extends AgitarTestCase {

    static Class TARGET_CLASS = CvTissue.class;

    public void testConstructor() throws Throwable {
        Institution owner = new Institution( "testCvTissueShortLab" );
        CvTissue cvTissue = new CvTissue( owner, "testCvTissueShortLab" );
        assertEquals( "cvTissue.xrefs.size()", 0, cvTissue.xrefs.size() );
        assertEquals( "cvTissue.getAliases().size()", 0, cvTissue.getAliases().size() );
        assertEquals( "cvTissue.shortLabel", "testCvTissueShortLab", cvTissue.getShortLabel() );
        assertEquals( "cvTissue.annotations.size()", 0, cvTissue.annotations.size() );
        assertSame( "cvTissue.getOwner()", owner, cvTissue.getOwner() );
    }

    public void testConstructorThrowsIllegalArgumentException() throws Throwable {
        try {
            new CvTissue( new Institution( "testCvTissueShortLab" ), "" );
            fail( "Expected IllegalArgumentException to be thrown" );
        } catch ( IllegalArgumentException ex ) {
            assertEquals( "ex.getMessage()", "Must define a non empty short label", ex.getMessage() );
            assertThrownBy( AnnotatedObjectUtils.class, ex );
        }
    }

    public void testConstructorThrowsNullPointerException() throws Throwable {
        try {
            new CvTissue( new Institution( "testCvTissueShortLab" ), null );
            fail( "Expected NullPointerException to be thrown" );
        } catch ( NullPointerException ex ) {
            assertEquals( "ex.getMessage()", "Must define a non null short label", ex.getMessage() );
            assertThrownBy( AnnotatedObjectUtils.class, ex );
        }
    }
}

