/**
 * Generated by Agitar build: Agitator Version 1.0.4.000276 (Build date: Mar 27, 2007) [1.0.4.000276]
 * JDK Version: 1.5.0_09
 *
 * Generated on 04-Apr-2007 08:30:40
 * Time to generate: 00:07.694 seconds
 *
 */

package agitar.uk.ac.ebi.intact.modelt; import uk.ac.ebi.intact.model.*;

import com.agitar.lib.junit.AgitarTestCase;

public class FieldTooLongExceptionAgitarTest extends AgitarTestCase {

    static Class TARGET_CLASS = FieldTooLongException.class;

    public void testConstructor() throws Throwable {
        FieldTooLongException fieldTooLongException = new FieldTooLongException( "testFieldTooLongExceptionValue", "testFieldTooLongExceptionFieldName", 100 );
        assertEquals( "fieldTooLongException.getMessage()", "Value too long for field testFieldTooLongExceptionFieldName(100): testFieldTooLongExceptionValue", fieldTooLongException.getMessage() );
    }
}

