/**
 * Generated by Agitar build: Agitator Version 1.0.4.000276 (Build date: Mar 27, 2007) [1.0.4.000276]
 * JDK Version: 1.5.0_09
 *
 * Generated on 04-Apr-2007 08:24:45
 * Time to generate: 00:10.094 seconds
 *
 */

package agitar.uk.ac.ebi.intact.modelt; import uk.ac.ebi.intact.model.*;

import com.agitar.lib.junit.AgitarTestCase;

public class IntactObjectImplAgitarTest extends AgitarTestCase {

    static Class TARGET_CLASS = IntactObjectImpl.class;

    public void testClone() throws Throwable {
        Institution result = ( Institution ) new Institution( "testIntactLabel" ).clone();
        assertNull( "result.getFullName()", result.getFullName() );
    }
}

