/**
 * Generated by Agitar build: Agitator Version 1.0.4.000276 (Build date: Mar 27, 2007) [1.0.4.000276]
 * JDK Version: 1.5.0_09
 *
 * Generated on 04-Apr-2007 08:29:17
 * Time to generate: 00:06.316 seconds
 *
 */

package agitar.uk.ac.ebi.intact.modelt; import uk.ac.ebi.intact.model.*;

import com.agitar.lib.junit.AgitarTestCase;

public class NotAnEntityExceptionAgitarTest extends AgitarTestCase {

    static Class TARGET_CLASS = NotAnEntityException.class;

    public void testConstructor() throws Throwable {
        NotAnEntityException notAnEntityException = new NotAnEntityException( Integer.class );
        assertEquals( "notAnEntityException.getMessage()", "Class is not annotated with @javax.persistence.Entity: class java.lang.Integer", notAnEntityException.getMessage() );
    }
}

